{% set name = "azure-data-tables" %}
{% set version = "12.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e0d5598113855f9114fd7671623d35509f83772970cfdc597901b35f42dc3134

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - azure-core <2.0.0,>=1.24.0
    - yarl >=1.0,<2.0
    - isodate >=0.6.0
    - typing-extensions >=4.3.0

test:
  imports:
    - azure.data.tables
    - azure.data.tables._generated
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/table/azure-table
  summary: Microsoft Azure Azure Data Tables Client Library for Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
    - TomAugspurger
